Add BinderHub app
stackhpc/azimuth-charts pull request #11
Opened 2023-11-06 17:02 UTC by sd109

2023-11-08 13:11 UTC, m-bull requested changes
I don't have any problems with this merging - demo seems to work nicely.

Maybe just clean up the errant commit to kubeflow-azimuth?

2023-11-14 11:42 UTC, mkjpryor requested changes
Nice work. Just a few small changes I think.

2023-11-14 11:42 UTC, mkjpryor commented on binderhub-azimuth/templates/registry.yml
> +      - image: docker.io/registry
This should be customisable via the values, e.g. like https://github.com/stackhpc/azimuth-identity-operator/blob/main/chart/values.yaml#L25-L29, and should use a specific tag.

2023-11-14 11:42 UTC, mkjpryor commented on binderhub-azimuth/templates/registry.yml
> +  name: binderhub-registry
Name should be templated to avoid conflicts between two BinderHubs in the same namespace.

2023-11-14 11:42 UTC, mkjpryor commented on binderhub-azimuth/templates/registry.yml
> +  name: binderhub-registry-creds
Name should be templated to avoid conflicts between two BinderHubs in the same namespace.

2023-11-14 11:42 UTC, mkjpryor commented on binderhub-azimuth/templates/registry.yml
> +  name: binderhub-registry-image-pull
Name should be templated to avoid conflicts between two BinderHubs in the same namespace.

2023-11-14 11:42 UTC, mkjpryor commented on binderhub-azimuth/templates/reservation-rbac.yml
> +  name: binderhub-zenith
Name should be templated to avoid conflicts between two BinderHubs in the same namespace.

2023-11-14 11:42 UTC, mkjpryor commented on binderhub-azimuth/templates/reservation-rbac.yml
> +  name: binderhub-zenith
Name should be templated to avoid conflicts between two BinderHubs in the same namespace.

2023-11-29 11:44 UTC, sd109 commented on kubeflow-azimuth/to-helm-chart.py
Done

2023-11-29 14:23 UTC, mkjpryor requested changes

2023-12-05 14:35 UTC, mkjpryor approved these changes
LGTM

2023-12-05 14:36 UTC, merged